sudo: false
dist: trusty
language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env:
        - CC="g++-9" CXX="g++-9"

script:
  - cmake -H. -Bbuild
  - cmake --build build
