sudo: false
dist: trusty
language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env:
        - COMPILER="g++-9"

script:
  - CC=${COMPILER} CXX=${COMPILER} cmake -H. -Bbuild
  - CC=${COMPILER} CXX=${COMPILER} cmake --build build
